### ISSUE TITLE
`make test` broken

### ISSUE THREAD

**Issue by rngtng** [bramp/js-sequence-diagrams#19]
when I run `make test` I'll get this:

```
$ make test
node grammar.js test

fs.js:381
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:381:19)
    at Object.fs.readFileSync (fs.js:208:28)
    at Object.commonjsMain [as main] (/Users/tobi/Projects/js/js-sequence-diagrams/grammar.js:394:32)
    at Object.<anonymous> (/Users/tobi/Projects/js/js-sequence-diagrams/grammar.js:398:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
make: *** [test] Error 1
```

any idea what's wrong ? thx

**Comment by bramp** [comment]
ok all fixed now.
