### ISSUE TITLE
Support for building on Windows

### ISSUE THREAD

**Issue by ComFreek** [bramp/js-sequence-diagrams#73]
I know that [Makefiles can be run on Windows](http://stackoverflow.com/questions/17158419/how-to-run-makefile-in-windows), but wouldn't it be easier (and more portable) to use [Gulp](https://github.com/gulpjs/gulp)?

**Comment by bruriaP** [comment]
how can i run it in window

**Comment by bruriaP** [comment]
D:\diagramgulp>gulp build
[12:00:58] Using gulpfile D:\diagramgulp\gulpfile.js
[12:00:58] Starting 'build'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Parse error on line 1:
(function () {  "use
-^
Expecting '%%', 'START', 'LEX_BLOCK', 'ACTION', 'OPTIONS', 'PARSE_PARAM', 'LEFT', 'RIGHT', 'NONASSOC', got 'ID'
    at Object.parseError (D:\diagramgulp\node_modules\ebnf-parser\parser.js:211:15)
    at Object.parse (D:\diagramgulp\node_modules\ebnf-parser\parser.js:269:22)
    at Object.parse (D:\diagramgulp\node_modules\ebnf-parser\ebnf-parser.js:5:55)
    at Jison_Generator [as constructor] (D:\diagramgulp\node_modules\jison\lib\jison.js:83:30)
    at (anonymous function) [as constructor] (D:\diagramgulp\node_modules\jison\lib\util\typal.js:23:28)
    at new o.constructor (D:\diagramgulp\node_modules\jison\lib\util\typal.js:77:70)
    at new Jison_Generator (D:\diagramgulp\node_modules\jison\lib\jison.js:1906:20)
    at DestroyableTransform._transform (D:\diagramgulp\node_modules\gulp-jison\index.js:24:44)
    at DestroyableTransform.Transform._read (D:\diagramgulp\node_modules\gulp-jison\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\diagramgulp\node_modules\gulp-jison\node_modules\readable-stream\lib\_stream_transform.js:172:12)

**Comment by bruriaP** [comment]
its not working

**Comment by ComFreek** [comment]
@bruriaP My fork is far behind this upstream repository, 117 commits to be precise. I would recommend building with the Makefile, see the [first comment in this thread](https://github.com/bramp/js-sequence-diagrams/issues/73#issue-39513834).
